package com.example.entity5.jpa1;

import java.io.Serializable;
import java.sql.*;
import javax.persistence.*;
import lombok.Data;
import lombok.ToString;

/**
 * Note: auto-generated by jpa-entity-generator
 */
@Data
@ToString
@Entity(name = "com.example.entity5.jpa1.BlogArticleTag")
@Table(name = "article_tag")
public class BlogArticleTag implements Serializable {

  public Integer getId() { return this.id; }

  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(name = "`id`", nullable = false)
  private Integer id;
  @Column(name = "`created_at`", nullable = false)
  private Timestamp createdAt;
  @ManyToOne
  @JoinColumn(name = "`tag_id`", referencedColumnName = "`id`", insertable = false, updatable = false)
  private Tag tag;
  @ManyToOne
  @JoinColumn(name = "`article_id`", referencedColumnName = "`id`", insertable = false, updatable = false)
  private BlogArticle article;
}