package com.example.entity3;

import jakarta.persistence.*;
import java.io.Serializable;
import java.sql.*;
import lombok.Builder;
import lombok.Data;
import lombok.ToString;

/**
 * Note: auto-generated by jpa-entity-generator
 */
@Data
@ToString
@Builder(toBuilder = true)
@Entity(name = "com.example.entity3.Blog")
@Table(name = "blog")
public class Blog implements Serializable {

  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(name = "\"id\"", nullable = false)
  private Integer id;
  @Column(name = "\"name\"", nullable = true)
  private String name;
  @Column(name = "\"active\"", nullable = true)
  private boolean active;
  @Column(name = "\"created_at\"", nullable = false)
  private Timestamp createdAt;
}