package com.example.entity3;

import jakarta.persistence.*;
import java.io.Serializable;
import java.sql.*;
import lombok.Data;
import lombok.ToString;

/**
 * Note: auto-generated by jpa-entity-generator
 */
@Data
@ToString
@Entity(name = "com.example.entity3.Tag")
@Table(name = "tag")
public class Tag implements Serializable {

  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(name = "\"id\"", nullable = false)
  private Integer id;
  @Column(name = "\"tag\"", nullable = true, length = 100)
  private String tag;
  @Column(name = "\"average\"", nullable = true, precision = 9, scale = 2)
  private java.math.BigDecimal average;
  @Column(name = "\"created_at\"", nullable = false)
  private Timestamp createdAt;
}