package com.example.entity;

import com.example.annotation.Experimental;
import com.example.util.ExpirationPredicate;
import java.io.Serializable;
import java.sql.*;
import javax.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

/**
 * Note: auto-generated by jpa-entity-generator
 * TODO: This A/B testing mechanism is no longer used
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Deprecated
@Entity(name = "com.example.entity.ABTest")
@Table(name = "abtest")
public class ABTest implements Serializable, ExpirationPredicate {

  @Id
  @Column(name = "\"identifier\"")
  private String identifier;
  @Column(name = "\"expiration_timestamp\"")
  private Integer expirationTimestamp;
  @Experimental(comment = "The expected data format is JSON")
  @Column(name = "\"config\"")
  private String config;
}