package com.example.entity;

import com.example.util.ExpirationPredicate;
import java.io.Serializable;
import java.sql.Clob;
import javax.persistence.*;
import lombok.Data;
import lombok.ToString;

/**
 * Note: auto-generated by jpa-entity-generator
 */
@Data
@ToString
@Entity(name = "com.example.entity.ABTest")
@Table(name = "ABTEST")
public class ABTest implements Serializable, ExpirationPredicate {


  @Id
  @Column(name = "IDENTIFIER", nullable = false)
  private String identifier;
  @Column(name = "EXPIRATION_TIMESTAMP", nullable = false)
  private Integer expirationTimestamp;
  @Column(name = "CONFIG")
  private Clob config;
}