package com.example.entity;

import java.io.Serializable;
import java.sql.*;
import javax.annotation.Nonnull;
import javax.annotation.Nullable;
import javax.persistence.*;
import lombok.Data;
import lombok.ToString;

/**
 * Note: auto-generated by jpa-entity-generator
 */
@Data
@ToString
@Entity(name = "com.example.entity.BlogArticleTag")
@Table(name = "article_tag")
public class BlogArticleTag implements Serializable {

  public Integer getId() { return this.id; }

  @Id
  @GeneratedValue
  @Column(name = "\"id\"", nullable = false)
  private int id;
  /**
   * database comment for article_id
   * The field is non-null value
   */
  @Column(name = "\"article_id\"", nullable = false)
  private int articleId;
  /**
   * database comment for blog_id
   * The field is non-null value
   */
  @Column(name = "\"tag_id\"", nullable = false)
  private int tagId;
  @Nonnull
  @Column(name = "\"created_at\"", nullable = false)
  private Timestamp createdAt;
}