package com.example.entity.jpa1;

import java.io.Serializable;
import java.sql.Clob;
import javax.persistence.*;
import lombok.Data;
import lombok.ToString;

/**
 * Note: auto-generated by jpa-entity-generator
 */
@Data
@ToString
@Entity(name = "com.example.entity.jpa1.Abtest")
@Table(name = "ABTEST")
public class Abtest implements Serializable {


  @Id
  @Column(name = "`IDENTIFIER`", nullable = false)
  private String identifier;
  @Column(name = "`EXPIRATION_TIMESTAMP`", nullable = false)
  private Integer expirationTimestamp;
  @Column(name = "`CONFIG`")
  private Clob config;
}