package com.example.entity.jpa1;

import java.io.Serializable;
import java.sql.*;
import javax.persistence.*;
import lombok.Data;
import lombok.ToString;

/**
 * Note: auto-generated by jpa-entity-generator
 */
@Data
@ToString
@Entity(name = "com.example.entity.jpa1.Tag")
@Table(name = "tag")
public class Tag implements Serializable {

  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(name = "`id`", nullable = false)
  private Integer id;
  @Column(name = "`tag`", nullable = true, length = 100)
  private String tag;
  @Column(name = "`average`", nullable = true, precision = 9, scale = 2)
  private java.math.BigDecimal average;
  @Column(name = "`created_at`", nullable = false)
  private Timestamp createdAt;
}