package com.example.entity2;

import java.io.Serializable;
import java.sql.*;
import javax.persistence.*;
import lombok.Data;
import lombok.ToString;

/**
 * Note: auto-generated by jpa-entity-generator
 */
@Data
@ToString
@Entity(name = "com.example.entity2.BlogArticle")
@Table(name = "article")
public class BlogArticle implements Serializable {

  public Integer getId() { return this.id; }

  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(name = "\"id\"")
  private Integer id;
  /**
   * database comment for blog_id
   */
  @Column(name = "\"blog_id\"")
  private Integer blogId;
  @Column(name = "\"name\"")
  private String name;
  @Deprecated
  @Column(name = "\"tags\"")
  private Clob tags;
  @Column(name = "\"created_at\"")
  private Timestamp createdAt;
}